### ISSUE TITLE
Assertions using a custom predicate

### ISSUE THREAD

**Issue by ylegat** [assertj/assertj-db#57] opened 2018-11-30 10:34 UTC
Hi!

Despite reading the documentation, I fail to see how I can run an assertion on a value using a custom predicate. This is necessary because I need to check a specific property of a value.

Did I miss something or is there currently no way of doing that?

**Comment by VanRoy** [comment] 2019-12-06 13:17
Duplicate of #24

**Comment by VanRoy** [comment] 2019-12-26 17:02
Implemented in release 1.3.0

**Closed by VanRoy** 2019-12-26 17:02 UTC
Labels: enhancement
